SELECT		MIN(Divedate) AS DivedateMin,
		MAX(Divedate) AS DivedateMax,
		MIN(Divetime) AS DivetimeMin,
		MAX(Divetime) AS DivetimeMax,
		AVG(Divetime) AS DivetimeAvg,
		SUM(Divetime) AS BottomTime,
		MIN(Depth) AS DepthMin,
		MAX(Depth) AS DepthMax,
		AVG(Depth) AS DepthAvg,
		ROUND(MIN(Watertemp),1) AS WatertempMin,
		ROUND(MAX(Watertemp),1) AS WatertempMax,
		ROUND(AVG(Watertemp),1) AS WatertempAvg,
		MIN(Airtemp) AS AirtempMin,
		MAX(Airtemp) AS AirtempMax,
		AVG(Airtemp) AS AirtempAvg
FROM		$_config[table_prefix]Logbook
